spring:
  application:
    name: cwh-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrChenWH/security-config.git
server:
  port: 8051
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8050}/eureka/